### ISSUE TITLE
oembed available? (podcasts support)

### ISSUE THREAD

**Issue by tassoman** [EldritchCafe/radio#21]
Hi there, some people asked to listen podcasts. Is it already possible? Maybe by oembed decodification? :thinking:

**Comment by wryk** [comment]
Not possible if not hosted on YT. The only player available right now uses the YT's IFrame player API.

Code is designed to be extendable for players (we had funkwhale in mind) but no additional backends has been added because of low usage outside youtube links and available development time.

**Comment by tassoman** [comment]
Diggin deeper into my user's request, question was for some kind of funkwhale posts. 
Being federated, following funkwhale accounts would be itself an aggregation. User can follow all podcasters in a "podcasts" list, and boom, this is a kind of aggregation ... Don't know either, if the effort is valuable.
BTW thanks for supporting and sharing!
