### ISSUE TITLE
Add Invidio.us support

### ISSUE THREAD

**Issue by Alamantus** [EldritchCafe/radio#5]
Hi there! Adding support for Invidio.us (a alternate lightweight YouTube front-end) would be super easy because it pulls its videos _from_ YouTube and it purposely has the same URL structure!

It looks like only the end of the `src/services/mastodon.js` file would need to be changed to include `invidio.us` in the list of domains.

**Comment by wryk** [comment]
Adding invidio.us domain in Youtube support is effectively really easy but will not provide the anonymity from Invidous in the app.

But since it doesn't hinder the possible addition of a real Invidious support in the future I don't see any drawback to do it.

**Comment by Alamantus** [comment]
@wryk Well, this is unfortunate timing: https://omar.yt/posts/stepping-away-from-open-source (in case you didn't see it already)

**Comment by wryk** [comment]
Well, I'll remove invidio.us support after the instance shutdown.
